export const difficultyTrainingData = {
  easy: [
    "I like apples",
    "She is my friend",
    "This is my book",
    "The dog is big",
    "He runs fast",
    "I go to school",
    "She likes music",
    "We play football",
    "The car is red",
    "I drink water",
    "This is a pen",
    "He is tall",
    "She has a cat",
    "I am happy",
    "We are friends",
    "The sun is bright",
    "I like coffee",
    "She reads books",
    "He plays soccer",
    "I go home"
  ],

  medium: [
    "I went to the market yesterday",
    "She has been studying English for two years",
    "We decided to travel abroad next summer",
    "He didn't know what to say",
    "The weather was surprisingly cold today",
    "She forgot to bring her umbrella",
    "They arrived earlier than expected",
    "I would like to visit Paris someday",
    "She enjoys reading novels in her free time",
    "He has worked there for quite a long time",
    "If the weather is nice, we can go outside",
    "The project will be finished by next week",
    "Although it was raining, we went out anyway",
    "He mentioned that he might be late",
    "She prefers tea to coffee in the morning",
    "We should complete this task before Friday",
    "I have visited many countries in Europe",
    "Last month, she decided to change her job",
    "When they arrived, everyone was already there",
    "The results showed that the plan was effective"
  ],

  hard: [
    "It took him years to overcome the trauma",
    "She reluctantly admitted her mistake",
    "The government implemented controversial policies",
    "He struggled to articulate his thoughts clearly",
    "The professor elaborated on complex theories",
    "Economic instability affected international markets",
    "While the evidence appeared convincing, the committee requested further review",
    "The researcher hypothesized that structural factors might significantly influence outcomes",
    "Notwithstanding substantial efforts, the organization continued experiencing unforeseen difficulties",
    "The committee determined that comprehensive revisions would be necessary before proceeding",
    "Having analyzed multiple scenarios, stakeholders ultimately selected the most sustainable approach",
    "Conversely, the decline of traditional systems has created unprecedented challenges for established institutions",
    "Although technological advancement offers remarkable capabilities, it simultaneously presents ethical dilemmas",
    "If governments prioritize preventive measures, long-term expenditures would likely decrease substantially",
    "The evolution of digital platforms has fundamentally transformed how societies organize themselves",
    "One consequence of rapid urbanization is the gradual erosion of community cohesion",
    "To effectively address systemic inequality, policymakers must examine structural barriers comprehensively",
    "I would argue that intrinsic motivation demonstrates greater efficacy than external incentive structures",
    "A nuanced understanding of historical context is essential when evaluating controversial decisions",
    "In retrospect, the project succeeded because we continuously refined our methodology and assumptions"
  ]
};

export const listeningDifficultyTrainingData = {
  easy: [
    "Open the door.",
    "Sit down, please.",
    "Turn off the light.",
    "We are at home.",
    "I need some water.",
    "The bus is late.",
    "He is my brother.",
    "Please call me.",
    "I can help you.",
    "She has a cat.",
    "Close the window.",
    "Stand up, please.",
    "Come here.",
    "Go away.",
    "Stop, please.",
    "Wait a moment.",
    "Be careful.",
    "Listen to me.",
    "Look at that.",
    "Do you understand?",
    "What is this?",
    "Where are you?",
    "Who is that?",
    "How are you?",
    "What time is it?",
    "This is good.",
    "It is cold today.",
    "We live here.",
    "She works there.",
    "I am fine."
  ],
  medium: [
    "The train arrives at half past six.",
    "Could you repeat that one more time?",
    "I left my wallet on the kitchen table.",
    "We should book the tickets in advance.",
    "The meeting has been moved to Thursday.",
    "Please take the second exit after the bridge.",
    "He said he might join us after work.",
    "I forgot to charge my phone last night.",
    "The weather forecast predicts heavy rain tomorrow.",
    "She usually studies in the library after class.",
    "The doctor said I should rest for a few days.",
    "We decided to travel abroad next summer.",
    "Can you help me with this project?",
    "The restaurant is just around the corner.",
    "She has been waiting for about an hour.",
    "If you need anything, feel free to call.",
    "The concert starts at seven o'clock tonight.",
    "He mentioned that he would be late.",
    "Please make sure you bring your passport.",
    "Although the road was crowded, we arrived on time.",
    "The flight was delayed because of bad weather.",
    "I usually go jogging in the morning.",
    "She prefers coffee to tea.",
    "They are planning to visit us next month.",
    "The price has increased since last year.",
    "He works as a teacher at the local school.",
    "Last week I attended an interesting conference.",
    "We should finish the report before deadline.",
    "The museum is closed on Mondays.",
    "Can I borrow your pen for a moment?"
  ],
  hard: [
    "Although the package was dispatched yesterday, it has not yet reached the warehouse.",
    "The lecturer emphasized that consistent revision significantly improves long term retention.",
    "Despite the traffic disruption, the delegation managed to arrive before the keynote began.",
    "Passengers are advised to remain seated until the aircraft comes to a complete stop.",
    "The committee concluded that the proposal required substantial financial restructuring.",
    "If the symptoms persist, you should consult a specialist without further delay.",
    "The announcement clarified that refunds would be processed within fourteen business days.",
    "Given the current constraints, we need a more sustainable operational strategy.",
    "The documentary illustrated how climate variability affects regional food security.",
    "Participants who submitted late applications were placed on a waiting list.",
    "Having thoroughly examined the evidence, the board reached a unanimous decision.",
    "Notwithstanding the additional funding, the project faced unforeseen complications.",
    "The researcher concluded that environmental factors played a decisive role in the outcome.",
    "While technological advancement offers significant advantages, it simultaneously raises ethical concerns.",
    "To effectively implement this policy, authorities must coordinate across multiple jurisdictional levels.",
    "The report indicated that structural reforms would require considerable organizational restructuring.",
    "Conversely, the decline of traditional media has created unprecedented opportunities for digital platforms.",
    "Should unexpected complications emerge, contingency procedures have been established.",
    "The evolution of artificial intelligence has fundamentally transformed multiple sectors of the economy.",
    "I would argue that maintaining institutional credibility depends as much on transparency as on performance metrics.",
    "A comprehensive understanding of historical context is essential for evaluating contemporary social developments.",
    "In retrospect, organizational success resulted from continuous evaluation and systematic refinement of strategies.",
    "Although initial projections were optimistic, subsequent data demonstrated the necessity of revised expectations.",
    "The committee established that only through coordinated inter-agency cooperation could meaningful progress occur.",
    "Given the complexity of the situation, stakeholders determined that multidisciplinary expertise would be essential.",
    "The analysis revealed that long-term sustainability required fundamental changes to existing operational frameworks.",
    "Participants were informed that procedural modifications would necessitate comprehensive retraining initiatives.",
    "The documentation specified that any deviations from established protocols must receive prior authorization.",
    "Having completed the preliminary assessment, the team proceeded with confidence to the implementation phase.",
    "The presentation demonstrated that economic factors and environmental considerations were inextricably intertwined."
  ]
};

export const speakingDifficultyTrainingData = {
  easy: [
    "My name is Anna.",
    "I live in Hanoi.",
    "I like reading books.",
    "This is my friend.",
    "I go to school by bus.",
    "My favorite food is noodles.",
    "I have one older sister.",
    "We play soccer on Sundays.",
    "I wake up at seven.",
    "I can speak a little English.",
    "I am a student.",
    "My parents are teachers.",
    "I have a dog.",
    "The weather is nice today.",
    "I like coffee.",
    "She is my mother.",
    "He is my father.",
    "They are my friends.",
    "I work hard.",
    "She is beautiful.",
    "The book is interesting.",
    "I am happy.",
    "He is tall.",
    "The day is sunny.",
    "I love my family.",
    "We are in the classroom.",
    "The car is fast.",
    "She writes letters.",
    "He plays guitar.",
    "I study English."
  ],
  medium: [
    "I usually spend my weekends helping my parents at home.",
    "If I have free time, I prefer going for a short walk.",
    "Last year I joined a course to improve my communication skills.",
    "In my opinion, learning by practice is more effective than memorizing rules.",
    "I would like to describe a place that is important to me.",
    "One challenge I often face is managing my time efficiently.",
    "I believe teamwork is essential for solving complex problems.",
    "When I was younger, I was afraid of speaking in front of a class.",
    "A healthy routine helps me stay focused during the day.",
    "I often use online videos to practice pronunciation at home.",
    "The most memorable trip I have taken was to Hue with my family.",
    "When I feel stressed, I usually go for a walk and listen to calm music.",
    "I think teamwork is important because difficult tasks are easier when people cooperate.",
    "A good leader should listen to others before making an important decision.",
    "One of the most valuable lessons I have learned is to stay patient during failure.",
    "I prefer studying in a quiet place because it helps me focus better.",
    "Last summer I went to the beach and had a wonderful time.",
    "I have visited my grandparents many times and we always have fun together.",
    "In my spare time, I like to watch films or read comic books.",
    "I would describe myself as friendly and easy-going with other people.",
    "The most exciting experience I had was traveling by train to another country.",
    "I enjoy spending time with my friends whether we are at home or outside.",
    "Learning a new skill takes time and dedication from the student.",
    "I believe that persistence is important for achieving any significant goal.",
    "My favorite hobby is painting because it helps me relax and express myself.",
    "I started learning English when I was about ten years old in primary school.",
    "I would say that understanding other cultures makes us more open-minded.",
    "Technology has changed the way we communicate with people around the world.",
    "I think it is important to help others when they need assistance.",
    "My dream is to travel around the world and experience different places."
  ],
  hard: [
    "From my perspective, technological advancement should be balanced with ethical responsibility.",
    "Had I planned more carefully, I could have avoided several unnecessary delays.",
    "One consequence of rapid urbanization is the gradual decline of community interaction.",
    "To address this issue effectively, we must examine both short term and structural factors.",
    "I would argue that intrinsic motivation plays a more decisive role than external rewards.",
    "While social media facilitates communication, it can also intensify misinformation.",
    "The experience taught me that resilience is built through repeated adaptation.",
    "If governments prioritized preventive policies, public health outcomes would improve considerably.",
    "A nuanced understanding of cultural context is crucial in international collaboration.",
    "In retrospect, the project succeeded because we continuously evaluated and refined our strategy.",
    "From my perspective, education should prepare students not only for employment but also for responsible participation in society.",
    "Although technology has made communication faster, it has also reduced the depth of many face-to-face interactions.",
    "If governments invested more consistently in preventive healthcare, long-term public spending would likely decrease.",
    "I would argue that true innovation depends as much on cultural openness as it does on financial support.",
    "One consequence of excessive dependence on artificial intelligence is the gradual erosion of critical human judgment.",
    "While economic growth is necessary, it should not come at the expense of environmental sustainability.",
    "The evolution of digital technology has fundamentally transformed how society organizes itself at both local and global scales.",
    "Conversely, the decline of traditional media has created unprecedented challenges for institutions that relied on established distribution channels.",
    "Notwithstanding the significant resources invested in this initiative, outcomes remained below expectations due to unforeseen external factors.",
    "To effectively address inequality, we must acknowledge that systemic barriers require comprehensive policy interventions.",
    "What makes sustainable development challenging is reconciling immediate economic needs with long-term environmental imperatives.",
    "The research demonstrates that cultural factors influence how individuals interpret and respond to novel situations.",
    "Having thoroughly considered multiple perspectives, one can argue that compromise often yields the most practical solutions.",
    "Should unexpected circumstances arise, organizations must possess sufficient adaptability to implement contingency procedures.",
    "I believe that meaningful progress requires commitment to continuous learning and willingness to challenge established assumptions.",
    "The analysis indicates that successfully navigating globalization necessitates understanding economic interdependencies across regions.",
    "Although standardization improves efficiency, it simultaneously risks homogenizing valuable cultural and linguistic diversity.",
    "In my view, effective leadership demands the ability to reconcile competing interests while maintaining ethical integrity.",
    "The committee concluded that addressing this complex problem would require input from multiple disciplinary perspectives.",
    "One could assert that the capacity to adapt to uncertainty distinguishes successful organizations from those that struggle."
  ]
};